# Generated by Django 6.1.1 on 2026-09-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(default='Agendado', max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.professores')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('falta', models.BooleanField(default=False)),
                ('atraso', models.BooleanField(default=False)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='cadastros.estudantes')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.disciplinas')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.professores')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_notas', models.AutoField(primary_key=True, serialize=False)),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')])),
                ('tipo_avaliacao', models.CharField(max_length=50)),
                ('nota_1', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nota_2', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nota_3', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('media', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('situacao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('RECUPERACAO', 'Recuperação'), ('REPROVADO', 'Reprovado')], default='RECUPERACAO', max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='cadastros.disciplinas')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='cadastros.estudantes')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estudante', 'disciplina', 'bimestre', 'tipo_avaliacao'), name='nota_unica_por_avaliacao')],
            },
        ),
    ]
