# Generated by Django 6.1.1 on 2026-09-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplinas', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('status', models.CharField(default='Ativa', max_length=20)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id_professores', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores', to='cadastros.disciplinas')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professores', to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id_responsaveis', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis', to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id_turmas', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=15)),
                ('sala', models.CharField(max_length=15)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='usuarios.escola')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='cadastros.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Estudantes',
            fields=[
                ('id_estudantes', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='usuarios.escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='cadastros.responsaveis')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='cadastros.turmas')),
            ],
        ),
        migrations.AddConstraint(
            model_name='disciplinas',
            constraint=models.UniqueConstraint(fields=('escola', 'codigo'), name='unique_codigo_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='professores',
            constraint=models.UniqueConstraint(fields=('escola', 'matricula'), name='unique_matricula_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='responsaveis',
            constraint=models.UniqueConstraint(fields=('escola', 'cpf'), name='unique_cpf_por_escola'),
        ),
        migrations.AddConstraint(
            model_name='estudantes',
            constraint=models.UniqueConstraint(fields=('escola', 'matricula'), name='unique_matricula_estudante_por_escola'),
        ),
    ]
