# Generated by Django 6.1.1 on 2026-09-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_reclamacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em andamento', 'Em andamento'), ('Resolvida', 'Resolvida')], max_length=50)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Reunioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_reuniao', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('participantes', models.IntegerField()),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.escola')),
            ],
        ),
    ]
